---
title: "Visualization_Regression"
author: "Chaytanya Kumar"
date: "4/26/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading Library and DataSet

```{r load libaries}
library(tidyverse)
library(broom)
library(GGally)
library(onewaytests)
library(lbutils)
```


```{r load data}
my_file <- read_csv("~/Documents/STAT_615_Regression/Regression_ Project/DataSet_final.csv")
dim(my_file)
summary(my_file)
view(my_file)
```
Here we have a sample size of 1228 observations with 21 variables.


## Exploratory Data Analysis : 

### Calculating the response rate 

```{r}

response <- table(my_file$response)
Responserate <- (response[2]/(response[1]+response[2]))*100
Responserate[2] <- (response[1]/(response[1]+response[2]))*100
names(Responserate) <- c(1,0)
Responserate


Res <- data.frame(response=c(1,0),
                  rate=c(40.06515,59.93485))
Res
Res$response =as.factor(Res$response)


ggplot(Res,aes(x=response,y=rate))+ 
  geom_bar(stat = "identity",fill = c("green", "red"))+
  labs(x="Response type (No/Yes)",y="Response Rate")

```
```{r box plot analysis}
boxplot(nps~response, data = my_file,col=c("red","green"))

boxplot(Sales2019~response,data=my_file,col=c("red","green"))


#gives you the mean of the Soles 2019 w.r.t to the responses (0 and 1)
salesres <- aggregate(Sales2019~response,data=my_file, FUN=mean)
salesres



boxplot(n_comp~response,data = my_file,col=c("red","green"))

boxplot(n_yrs~response,data = my_file,col=c("red","green"))

```

```{r  b1Sales and response}
B1Sales0 <- subset(my_file, B1Sales2019!=0)   #Created the subset of Channel Partners who have purchased B1 product
boxplot(B1Sales2019~response,data = B1Sales0,col=c("red","green"))

```

```{r buyingfrequency and response}

boxplot(BuyingFrequency2019~response,data=my_file,col=c("red","green"))



boxplot(BrandEngagement~response,data=my_file,col=c("red","green"))

```

```{r}
salesres$response<- as.factor(salesres$response)
ggplot(data=salesres,aes(x=response,y=Sales2019))+
  geom_bar(stat="identity",fill=c("red","green"))+
  labs(x="Response(No/Yes)",y="Sales2019",title="Average Sales of Channel Partners")

```



```{r Email rate}
Rate <- function(x)(mean(x)*100)

  Email_count <- aggregate(response~email,data = my_file,FUN=length)
  Email_count$response <- as.factor(Email_count$response)
  
  Emailrate  <- aggregate(response~email,data=my_file,FUN=Rate)
head(Emailrate)

Email_count$response_count <- (Email_count$response*Emailrate$response)/100

Email_Value<- paste0("(",Email_count$response_count,"/",Email_count$response,")")

Emailrate$email <- as.factor(Emailrate$email)

 
ggplot(Emailrate,aes(x=email,y=response))+
  geom_bar(stat='identity',fill="blue")+
  geom_text(aes(label=Email_Value),vjust=-0.2)+
  labs(x="No. of Emails",y="Response_rate",title = "Response Rate via Email")


Email_Table <-cbind(Email_count,Emailrate$response)
names(Email_Table)[3]<- "Response_Rate"
Email_Table$Response_Rate <- round(Email_Table$Response_Rate,2)
Email_Table


```


```{r SMS rate}


  #Calculate Response rate of the Channel Partners contacted via SMS  

SMSrate  <- aggregate(response~sms,data=my_file,FUN=Rate)
head(SMSrate)
SMS_count <- aggregate(response~sms,data=my_file,FUN=length)
SMS_count$response <- as.factor(SMS_count$response)

SMS_count$response_count <- (SMS_count$response*SMSrate$response)/100

SMS_Value<- paste0("(",SMS_count$response_count,"/",SMS_count$response,")")


SMSrate$sms <- as.factor(SMSrate$sms)
library(ggplot2)
ggplot(SMSrate,aes(x=sms,y=response))+
  geom_bar(stat="identity",fill="blue")+
  geom_text(aes(label=SMS_Value,vjust=-0.3))+
  labs(x="No. of SMS",y="Responserate",title="Response Rate via SMS")

```


```{r Call rate}
#Calculate Response rate of the Channel Partners contacted via Call

Callrate  <- aggregate(response~call,data=my_file,FUN=Rate)
head(Callrate)

Call_count <- aggregate(response~call,data=my_file,FUN=length)
Call_count$response <- as.factor(Call_count$response)


Call_count$response_count <- (Call_count$response*Callrate$response)/100

Call_Value<- paste0("(",Call_count$response_count,"/",Call_count$response,")")

Callrate$call <- as.factor(Callrate$call)

ggplot(Callrate,aes(x=call,y=response))+
  geom_bar(stat="identity",fill="blue")+
  geom_text(aes(label=Call_Value,vjust=-0.3))+
  labs(x="No. of Calls",y="Responserate",title="Response rate via Calls")


```


```{r Engagement}

Brand1 <- subset(my_file,BrandEngagement!=0)
dim(Brand1)
Brand <- aggregate(response~BrandEngagement,data=Brand1,FUN=Rate)
head(Brand)

Brand_count <- aggregate(response~BrandEngagement, data = Brand1,FUN = length)
Brand_count

Brand_count$response_count <-(Brand_count$response*Brand$response)/100
Brand_count

Brand_Value<- paste0("(",Brand_count$response_count,"/",Brand_count$response,")")



Brand$BrandEngagement <- as.factor(Brand$BrandEngagement)

ggplot(Brand,aes(x=BrandEngagement,y=response))+
  geom_bar(stat="identity",fill="blue")+
  geom_text(aes(label=Brand_Value,vjust=-0.3))+
  labs(x="No. of Brands",y="Responserate",title="Response rate to BrandEngagement")
```

```{r Loyalty w.r.t response}

Loyalty <- aggregate(response~loyalty,data=my_file,FUN=Rate)
head(Loyalty)

Loyalty$loyalty <- as.factor(Loyalty$loyalty)

ggplot(Loyalty,aes(x=loyalty,y=response))+
  geom_bar(stat="identity",fill="blue")+
  labs(x="Loyalty",y="Responserate",title="Response rate to Loyalty")


```

```{r buyingfrequency & response}

#Buying Frequency

B1 <- aggregate(response~BuyingFrequency2019,data = my_file,FUN=length)
B1
B2 <- aggregate(response~BuyingFrequency2019,data=my_file,FUN=Rate)
B2$BuyingFrequency2019 <- as.factor(B2$BuyingFrequency2019)



B1$response_count <- (B1$response*B2$response)/100

B1_Value<- paste0("(",B1$response_count,"/",B1$response,")")


ggplot(B2,aes(x=BuyingFrequency2019,y=response))+
  geom_bar(stat="identity",fill="blue")+
  geom_text(aes(label=B1_Value,vjust=-0.2))+
  labs(x="Buying Frequencies",y="Responserate",title="Response rate to BuyingFrequency")



```


##TABLES:

```{r loyalty response rate}

#Loyalty table
 
 l2<- aggregate(response~loyalty,data=my_file,FUN=length)
names(l2)[2]<- "No_Of_CP"
l3<- aggregate(response~loyalty,data = my_file,FUN=sum)
names(l3)[2]<-"Response_count"
l4 <- round(aggregate(response~loyalty,data = my_file,FUN=Rate),2)
names(l4)[2] <- "Response_rate"

Loyalty_Table <- cbind(l2,l3[2],l4[2])
Loyalty_Table

```



```{r Combination of all 3}



#Linear combination of Email + call + Sms

ESC <- aggregate(response~email+sms+call,data=my_file,FUN= Rate)
ESC_Length<- aggregate(response~email+sms+call,data=my_file,FUN= length)

Overall_Table<- data.frame(cbind(ESC$email,ESC$sms,ESC$call,ESC$response,ESC_Length$response))

Overall_Table <- setNames(Overall_Table, c("email","sms","call","response_rate","response_count"))
Overall_Table
Overall_Response_Final <- subset(Overall_Table,response_count>20 )
dim(Overall_Response_Final)

Overall_Response_Final$response_rate <- round(Overall_Response_Final$response_rate,2)
Overall_Response_Final[order(-Overall_Response_Final$response_rate),]


```

